// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaLGfcGsbG-vC1NuEtpp8ssSlUf0dpbsE',
    appId: '1:842348694467:web:8eecc791545923da0bcb76',
    messagingSenderId: '842348694467',
    projectId: 'dnpp-402403',
    authDomain: 'dnpp-402403.firebaseapp.com',
    storageBucket: 'dnpp-402403.appspot.com',
    measurementId: 'G-X1D4S88YD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFVXM0uVcVp5_koBeUPZbipKcDDrg4C0s',
    appId: '1:842348694467:android:97e03afe4aaf420d0bcb76',
    messagingSenderId: '842348694467',
    projectId: 'dnpp-402403',
    storageBucket: 'dnpp-402403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-zJ8A6CuZjEiNAVvU-k3ZxNs2YO8uFvE',
    appId: '1:842348694467:ios:335d2385fc1d6d5d0bcb76',
    messagingSenderId: '842348694467',
    projectId: 'dnpp-402403',
    storageBucket: 'dnpp-402403.appspot.com',
    androidClientId: '842348694467-j7bgugket5upe4296g7osjih63qsnet9.apps.googleusercontent.com',
    iosClientId: '842348694467-l2rof5tlp78n0943gs38s170ve6ukhb4.apps.googleusercontent.com',
    iosBundleId: 'com.simonwork.dnpp.dnpp',
  );
}
